<a href="https://colab.research.google.com/github/sebington/learning_python/blob/main/PML12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
np.random.seed(0)
A = np.random.randint(0, 10, [2, 3])
A

array([[5, 0, 3],
       [3, 7, 9]])

In [4]:
A.sum()

27

In [5]:
A.sum(axis=0)

array([ 8,  7, 12])

In [6]:
A.sum(axis=1)

array([ 8, 19])

In [7]:
A.cumsum() # 5 + 0 + 3 + 3 + 7 etc.

array([ 5,  5,  8, 11, 18, 27])

In [8]:
A.prod() # produit = 0 car il y a un zéro dans le tableau

0

In [9]:
A.cumprod() # produit cumulé

array([5, 0, 0, 0, 0, 0])

In [10]:
A.min(axis=0) # valeur min en balayant verticalement de gauche à droite

array([3, 0, 3])

In [11]:
# pour trouver la position du minimum selon l'axe vertical
A.argmin(axis=0) # renvoie les indexes de chaque colonne

array([1, 0, 0])

In [21]:
B = np.array([1, 3, -2, 5])
B.sort() # sort trie les éléments
B

array([-2,  1,  3,  5])

In [22]:
B = np.array([1, 3, -2, 5])
B.argsort() # argsort renvoie les indexes triés

array([2, 0, 1, 3])